### ISSUE TITLE
NPE retrieveLeaderboardScore

### ISSUE THREAD

**Issue by mobaras** [mauville-technologies/PGSGP#1]
Would be nice if you could fix this:

java.lang.NullPointerException: score must not be null
	at io.cgisca.godot.gpgs.leaderboards.LeaderboardsController$retrieveLeaderboardScore$1.onSuccess(LeaderboardsController.kt:58)
	at io.cgisca.godot.gpgs.leaderboards.LeaderboardsController$retrieveLeaderboardScore$1.onSuccess(LeaderboardsController.kt:17)
	at com.google.android.gms.tasks.zzn.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
	at android.os.Handler.handleCallback(Handler.java:883)

**Comment by Ozzadar** [comment]
I'll take a look. For some reason this didn't reach my inbox =/
